# Generated by Django 5.2.2 on 2025-07-04 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-date"]},
        ),
    ]
