# Generated by Django 5.2.2 on 2025-07-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_post_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="subtitle",
            field=models.CharField(default="Some post subtitle", max_length=200),
            preserve_default=False,
        ),
    ]
