# Generated by Django 5.2.2 on 2025-07-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_post_options_post_publish_post_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(max_length=200, unique_for_date="publish"),
        ),
    ]
